name: Build Carpenpi image
on: [push,release]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Change these when updating to new version of raspberry pi OS
      IMG_URL: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-lite.zip
      PI_ZIP: 2021-01-11-raspios-buster-armhf-lite.zip
      PI_ZIP_CHECKSUM: d49d6fab1b8e533f7efc40416e98ec16019b9c034bc89c59b83d0921c2aefeef
      PI_IMG: 2021-01-11-raspios-buster-armhf-lite.img
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      #- name: Install QEMU
        #run: sudo apt-get install -y qemu-system-arm qemu-efi
      - name: Download base image
        run: wget ${{ env.IMG_URL }}
      - name: Match checksum
        uses: Flurb/verify-file-checksum-action@v2
        with:
          fileUrl: "file://${{ env.PI_ZIP }}"
          checksum: ${{ env.PI_ZIP_CHECKSUM }}
          algorithm: 'SHA256'
