name: Build Carpenpi image
on: 
  push:
    branches: 
      - github_actions
  workflow_dispatch:
  release:
    types: [publish]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        path: checkout
    - name: Install Dependencies
      run: sudo apt-get install unzip git wget qemu-system-arm qemu-efi expect vim-tiny fdisk e2fsprogs mtools zip xz-utils
    - name: Build Image
      run: | 
        cd checkout/build_img
        sudo ./build_img.sh
    - name: Upload image as release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: checkout/build_img/release.zip
          asset_name: release.zip
          asset_content_type: application/zip
