name: Build Carpenpi image
on: 
  push:
    branches: 
      - github_actions
    tags:
      - 'v*'
  workflow_dispatch:
  release:
    types: [publish]

jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-22.04
    steps:
    - name: Check out repository code
      if: startsWith(github.ref, 'refs/tags/')    
      uses: actions/checkout@v2
      with:
        path: checkout
    - name: Install Dependencies
      if: startsWith(github.ref, 'refs/tags/')  
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y update
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y install unzip git wget qemu-system-arm qemu-efi expect vim-tiny fdisk e2fsprogs mtools zip xz-utils libcurl4-openssl-dev
    - name: Build Image
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GIT_TAG: ${GITHUB_REF#refs/tags/}
      run: | 
        cd checkout
        mkdir output
        sudo bash -x build_img/build_img.sh $PWD/output
        echo ::set-output name=version::${GIT_TAG}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          #files: checkout/output/release-${steps.prep.outputs.version}.zip
          files: | 
            checkout/output/release.zip
            checkout/output/release.z01
            checkout/output/img.sha256
 
          
